<script setup>
const { user } = useAuth()
const selectedDate = shallowRef(jalaliToday())
const period = ref('اونۍ')
const department = ref('ټولې څانګې')
const search = ref('')
const customize = ref(false)
const detail = ref(null)
const toast = useToast()
const widgets = ref([{ id: 'visits', label: 'د ناروغانو تګ راتګ', visible: true }, { id: 'distribution', label: 'د ناروغانو وېش', visible: true }, { id: 'patients', label: 'وروستي ناروغان', visible: true }, { id: 'activity', label: 'وروستي فعالیتونه', visible: true }])
onMounted(() => { try { const saved = JSON.parse(localStorage.getItem('roghtia-widgets') || 'null'); if (Array.isArray(saved) && saved.length === 4 && new Set(saved.map(w => w.id)).size === 4 && saved.every(w => widgets.value.some(x => x.id === w.id) && typeof w.visible === 'boolean')) widgets.value = saved } catch {} })
watch(widgets, value => { if (import.meta.client) localStorage.setItem('roghtia-widgets', JSON.stringify(value)) }, { deep: true })
function move(index, delta) { const next = index + delta; if (next < 0 || next >= widgets.value.length) return; const list = [...widgets.value]; [list[index], list[next]] = [list[next], list[index]]; widgets.value = list }
const scope = computed(() => (period.value === 'میاشت' ? 4 : period.value === 'ورځ' ? .18 : 1) * (department.value === 'ټولې څانګې' ? 1 : .6) * (selectedDate.value.compare(jalaliToday()) === 0 ? 1 : .85))
const stats = computed(() => [
  { label: 'ټول ناروغان', value: Math.round(1284 * scope.value), change: 12.8, icon: 'i-lucide-users-round', tone: 'teal', points: '0,26 10,22 20,24 30,15 40,18 50,11 60,14 70,6 80,10 90,4 105,2' },
  { label: 'د نن ورځې مراجعین', value: Math.round(48 * scope.value), change: 8.2, icon: 'i-lucide-stethoscope', tone: 'blue', points: '0,25 12,25 22,18 32,21 42,11 52,16 62,8 72,13 85,7 95,9 105,3' },
  { label: 'ثبت شوې نسخې', unit: 'نسخې', value: Math.round(36 * scope.value), change: 6.4, icon: 'i-lucide-clipboard-plus', tone: 'purple', points: '0,27 10,23 20,25 30,16 40,20 50,12 60,15 70,11 80,13 90,5 105,3' },
  { label: 'بشپړې شوې لیدنې', unit: 'لیدنې', value: Math.round(42 * scope.value), change: 10.5, icon: 'i-lucide-heart-pulse', tone: 'orange', points: '0,28 12,23 22,25 32,19 42,21 52,12 62,15 72,8 82,11 94,4 105,2' }
])
const days = ['شنبه', 'یکشنبه', 'دوشنبه', 'سه‌شنبه', 'چهارشنبه', 'پنجشنبه', 'جمعه']
const chartValues = computed(() => [28, 42, 34, 58, 46, 68, 52].map(n => Math.round(n * scope.value)))
const chartIndex = ref(3)
const patients = [
  { name: 'احمد ولي', initials: 'ا و', age: 32, gender: 'نارینه', code: 'PT-1024', type: 'عمومي معاینه', time: '09:30', status: 'بشپړ شوی', tone: 'teal' },
  { name: 'فاطمه احمدي', initials: 'ف ا', age: 28, gender: 'ښځینه', code: 'PT-1023', type: 'بیا کتنه', time: '10:00', status: 'په تمه', tone: 'purple' },
  { name: 'محمد عمر', initials: 'م ع', age: 45, gender: 'نارینه', code: 'PT-1022', type: 'عمومي معاینه', time: '10:30', status: 'بشپړ شوی', tone: 'blue' },
  { name: 'مریم رحیمي', initials: 'م ر', age: 24, gender: 'ښځینه', code: 'PT-1021', type: 'بیا کتنه', time: '11:00', status: 'د معاینې لاندې', tone: 'orange' }
]
const filteredPatients = computed(() => patients.filter(p => (p.name + p.code).toLowerCase().includes(search.value.toLowerCase()) && (department.value === 'ټولې څانګې' || p.type === department.value)))
function exportReport() { const rows = [['نېټه', 'شاخص', 'شمېر'], ...stats.value.map(s => [formatJalali(selectedDate.value), s.label, s.value])]; const blob = new Blob(['\uFEFF' + rows.map(r => r.join(',')).join('\r\n')], { type: 'text/csv;charset=utf-8;' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `roghtia-${selectedDate.value.toString()}.csv`; a.click(); URL.revokeObjectURL(url); toast.add({ title: 'راپور ښکته شو', description: 'د بېلګې معلوماتو راپور چمتو شو.', icon: 'i-lucide-check' }) }
</script>
<template>
  <div class="dashboard">
    <div class="page-heading"><div><div class="eyebrow"><span /> ستاسو د کلینیک یوه روښانه لیدنه</div><h1>د روغتیا لنډیز</h1><p>ښه راغلاست، {{ user?.userName }}! ستاسو د نن ورځې د پاملرنې انځور.</p></div><div class="heading-actions"><UButton color="neutral" variant="outline" icon="i-lucide-sliders-horizontal" @click="customize = true">د لنډیز تنظیم</UButton><UButton icon="i-lucide-download" @click="exportReport">راپور ښکته کول</UButton></div></div>
    <section class="welcome-banner"><div class="welcome-copy"><span class="banner-label"><span class="live-dot" /> هره پاملرنه، یو نوی امید</span><h2>د سالم ژوند په لور، یو ګام وړاندې.</h2><p>ستاسو پاملرنه توپیر رامنځته کوي. موږ ستاسو ترڅنګ یو، په هر ګام کې.</p><div class="banner-meta"><span><UIcon name="i-lucide-calendar-days" />{{ formatJalali(selectedDate, true) }}</span></div></div><div class="medical-art" aria-hidden="true"><div class="orbit orbit-one" /><div class="orbit orbit-two" /><span class="art-plus plus-one">+</span><span class="art-plus plus-two">+</span><div class="art-heart"><UIcon name="i-lucide-heart-pulse" /></div><div class="art-float"><UIcon name="i-lucide-shield-check" /><span>پاملرنه او باور</span></div><span class="art-dot" /></div></section>
    <div class="filter-row"><div class="section-label"><span class="section-mark" /><h2>د کلینیک عمومي وضعیت</h2><span class="subtle">ژوند ته نږدې، پاملرنې ته ژمن</span></div><div class="filters"><USelect v-model="department" :items="['ټولې څانګې', 'عمومي معاینه', 'بیا کتنه']" aria-label="څانګه" class="department-select" /><JalaliPicker v-model="selectedDate" /></div></div>
    <div class="stats-grid"><StatCard v-for="stat in stats" :key="stat.label" v-bind="stat" /></div>
    <div class="widget-grid">
      <template v-for="widget in widgets.filter(w => w.visible)" :key="widget.id">
        <WidgetPanel v-if="widget.id === 'visits'" class="visits-widget" title="د ناروغانو تګ راتګ" subtitle="د مراجعینو او بشپړو شویو لیدنو پرتله">
          <template #action><div class="period-switch"><button v-for="p in ['ورځ', 'اونۍ', 'میاشت']" :key="p" :class="{ selected: period === p }" @click="period = p">{{ p }}</button></div></template>
          <div class="chart-summary"><strong>{{ localNumber(Math.round(328 * scope)) }}<small>لیدنې</small></strong><span class="positive">↗ 12.8٪ <span>د تېرې مودې په پرتله</span></span><div class="chart-legend"><span><i />مراجعین</span><span><i />بشپړې لیدنې</span></div></div>
          <div class="chart" role="group" aria-label="د لیدنو متقابل چارټ"><div class="chart-y"><span v-for="n in [80, 60, 40, 20, 0]" :key="n">{{ localNumber(Math.round(n * scope)) }}</span></div><div class="chart-body"><div class="chart-lines"><i v-for="n in 5" :key="n" /></div><svg viewBox="0 0 700 170" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#20b4aa" stop-opacity=".22" /><stop offset="100%" stop-color="#20b4aa" stop-opacity="0" /></linearGradient></defs><path d="M0 120 C45 120 65 80 116 90 S180 120 233 105 S305 25 350 45 S415 100 467 72 S535 4 583 20 S650 62 700 48 L700 170 L0 170Z" fill="url(#area)"/><path d="M0 120 C45 120 65 80 116 90 S180 120 233 105 S305 25 350 45 S415 100 467 72 S535 4 583 20 S650 62 700 48" fill="none" stroke="#16a99e" stroke-width="3"/><path d="M0 147 C50 147 70 110 116 121 S185 145 233 131 S300 75 350 86 S415 125 467 108 S535 55 583 65 S650 102 700 86" fill="none" stroke="#99c9cd" stroke-width="2" stroke-dasharray="6 5"/></svg><div class="chart-hover"><button v-for="(day, i) in days" :key="day" :aria-label="`${day}: ${localNumber(chartValues[i])} لیدنې`" @mouseenter="chartIndex = i" @focus="chartIndex = i" @click="chartIndex = i"><span v-if="chartIndex === i" class="chart-tooltip">{{ localNumber(chartValues[i]) }} لیدنې<small>{{ day }}</small></span></button></div><div class="chart-x"><span v-for="day in days" :key="day" :title="day"><span class="chart-day-full">{{ day }}</span><span class="chart-day-short">{{ JALALI_WEEKDAY_LABELS[day] || day }}</span></span></div></div></div>
        </WidgetPanel>
        <WidgetPanel v-else-if="widget.id === 'distribution'" class="distribution-widget" title="د ناروغانو وېش" subtitle="د لیدنې د ډول له مخې"><template #action><UIcon name="i-lucide-chart-pie" class="muted-icon" /></template><div class="donut"><div><strong>{{ localNumber(Math.round(328 * scope)) }}</strong><span>ټولې لیدنې</span></div></div><div class="distribution-list"><div><span><i class="legend-dot" />عمومي معاینه</span><b>60٪ <small>{{ localNumber(Math.round(197 * scope)) }}</small></b></div><div><span><i class="legend-dot light" />بیا کتنه</span><b>25٪ <small>{{ localNumber(Math.round(82 * scope)) }}</small></b></div><div><span><i class="legend-dot pale" />مشوره</span><b>15٪ <small>{{ localNumber(Math.round(49 * scope)) }}</small></b></div></div></WidgetPanel>
        <WidgetPanel v-else-if="widget.id === 'patients'" class="patients-widget" title="وروستي ناروغان" subtitle="د نن ورځې ثبت شوي مراجعین"><template #action><UButton to="/patients" variant="link" trailing-icon="i-lucide-arrow-left">ټول ناروغان</UButton></template><div class="table-search"><UInput v-model="search" icon="i-lucide-search" placeholder="د ناروغ نوم یا پېژندپاڼه ولټوئ..." aria-label="د ناروغانو لټون" class="w-full" /></div><div class="table-scroll"><table><thead><tr><th>ناروغ</th><th>د لیدنې ډول</th><th>وخت</th><th>حالت</th><th><span class="sr-only">جزیات</span></th></tr></thead><tbody><tr v-for="patient in filteredPatients" :key="patient.code"><td><div class="patient-cell"><span class="patient-avatar" :class="patient.tone">{{ patient.initials }}</span><span><strong>{{ patient.name }}</strong><small>{{ localNumber(patient.age) }} کلن · {{ patient.gender }}</small></span></div></td><td>{{ patient.type }}</td><td class="time-cell">{{ patient.time }}</td><td><span class="status" :class="{ waiting: patient.status === 'په تمه', progress: patient.status === 'د معاینې لاندې' }"><i />{{ patient.status }}</span></td><td><UButton icon="i-lucide-chevron-left" variant="ghost" color="neutral" :aria-label="`${patient.name} جزیات`" @click="detail = patient" /></td></tr><tr v-if="!filteredPatients.length"><td colspan="5" class="empty-table">کوم ناروغ ونه موندل شو.</td></tr></tbody></table></div><div class="table-footer"><span>{{ localNumber(filteredPatients.length) }} ناروغان ښودل کېږي</span><span><span class="live-dot" />د بېلګې معلومات</span></div></WidgetPanel>
        <WidgetPanel v-else-if="widget.id === 'activity'" class="activity-widget" title="وروستي فعالیتونه" subtitle="د کلینیک د چارو تازه حال"><template #action><span class="today-tag">نن</span></template><div class="timeline"><div v-for="(event, i) in [{ title: 'نوې نسخه ثبت شوه', text: 'د احمد ولي لپاره عمومي نسخه', icon: 'i-lucide-clipboard-plus', time: '5 دقیقې وړاندې' }, { title: 'نوی ناروغ ثبت شو', text: 'فاطمه احمدي د ناروغانو لېست ته زیاته شوه', icon: 'i-lucide-user-round-plus', time: '15 دقیقې وړاندې' }, { title: 'لیدنه بشپړه شوه', text: 'د محمد عمر معاینه بشپړه شوه', icon: 'i-lucide-check', time: '30 دقیقې وړاندې' } ]" :key="event.title" class="timeline-item"><span class="timeline-icon" :class="['teal', 'blue', 'purple'][i]"><UIcon :name="event.icon" /></span><div><h3>{{ event.title }}</h3><p>{{ event.text }}</p><small>{{ event.time }}</small></div></div></div><div class="care-note"><UIcon name="i-lucide-heart-handshake" /><div><strong>ښه پاملرنه له ښه نظم پیلېږي.</strong><p>روغتیا، ستاسو د هرې ورځې ملګری.</p></div></div></WidgetPanel>
      </template>
    </div>
    <footer class="page-footer"><span>روغتیا <span>•</span> د غوره پاملرنې لپاره جوړ شوی</span><span><UIcon name="i-lucide-shield-check" /> ستاسو پاملرنه، زموږ لومړیتوب</span></footer>
    <UModal v-model:open="customize" title="د لنډیز تنظیم" description="ویجټونه ښکاره، پټ یا پورته او ښکته کړئ."><template #body><div v-for="(w, i) in widgets" :key="w.id" class="widget-option"><USwitch v-model="w.visible" :label="w.label" /><div><UButton icon="i-lucide-arrow-up" variant="ghost" :disabled="i === 0" aria-label="پورته" @click="move(i, -1)" /><UButton icon="i-lucide-arrow-down" variant="ghost" :disabled="i === widgets.length - 1" aria-label="ښکته" @click="move(i, 1)" /></div></div><p class="saved-note">بدلونونه په دې وسیله په خپله خوندي کېږي.</p></template></UModal>
    <UModal :open="!!detail" title="د ناروغ لنډ معلومات" description="دا معلومات یوازې بېلګه ده." @update:open="detail = null"><template #body><div v-if="detail" class="patient-detail"><span class="patient-avatar" :class="detail.tone">{{ detail.initials }}</span><h2>{{ detail.name }}</h2><p>{{ localNumber(detail.age) }} کلن · {{ detail.gender }}</p><p>{{ detail.type }} · {{ detail.status }}</p><p>{{ formatJalali(selectedDate) }} — {{ detail.time }}</p></div></template></UModal>
  </div>
</template>


