// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoghtiaSystem_JahidKawa.Server.Data;

#nullable disable

namespace RoghtiaSystem_JahidKawa.Server.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("RoghtiaSystem_JahidKawa.Server.Data.Models.DoctorInformation", b =>
                {
                    b.Property<int>("LoggedInUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("DoctorLogo")
                        .HasColumnType("BLOB");

                    b.Property<string>("DoctorNameEnglish")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("DoctorNamePashto")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("DoctorPhoto")
                        .HasColumnType("BLOB");

                    b.Property<string>("DoctorProfessionEnglish")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DoctorProfessionPashto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("HospitalLogo")
                        .HasColumnType("BLOB");

                    b.Property<string>("HospitalNamePashto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("LoggedInUserId");

                    b.ToTable("DoctorInformation");
                });

            modelBuilder.Entity("RoghtiaSystem_JahidKawa.Server.Data.Models.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Id");

                    b.ToTable("Medications", t =>
                        {
                            t.HasCheckConstraint("CK_Medications_Quantity", "Quantity >= 0");
                        });
                });

            modelBuilder.Entity("RoghtiaSystem_JahidKawa.Server.Data.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Code")
                        .IsUnique();

                    b.HasIndex("UserId", "Id");

                    b.ToTable("Patients", t =>
                        {
                            t.HasCheckConstraint("CK_Patients_Age", "Age BETWEEN 0 AND 150");
                        });
                });

            modelBuilder.Entity("RoghtiaSystem_JahidKawa.Server.Data.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PINCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int>("PINFailedAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PINLockedUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<int>("PasswordVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("User");

                    b.Property<int>("TokenVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RoghtiaSystem_JahidKawa.Server.Data.Models.DoctorInformation", b =>
                {
                    b.HasOne("RoghtiaSystem_JahidKawa.Server.Data.Models.Users", null)
                        .WithOne()
                        .HasForeignKey("RoghtiaSystem_JahidKawa.Server.Data.Models.DoctorInformation", "LoggedInUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoghtiaSystem_JahidKawa.Server.Data.Models.Medication", b =>
                {
                    b.HasOne("RoghtiaSystem_JahidKawa.Server.Data.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RoghtiaSystem_JahidKawa.Server.Data.Models.Patient", b =>
                {
                    b.HasOne("RoghtiaSystem_JahidKawa.Server.Data.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
